var annotated_dup =
[
    [ "AbstractDriverComponent", "class_abstract_driver_component.html", "class_abstract_driver_component" ],
    [ "AbstractSocketConnector", "class_abstract_socket_connector.html", "class_abstract_socket_connector" ],
    [ "CallbackHandler", "class_callback_handler.html", "class_callback_handler" ],
    [ "ClientSocketConnector", "class_client_socket_connector.html", "class_client_socket_connector" ],
    [ "CRC", "class_c_r_c.html", "class_c_r_c" ],
    [ "DAQDriver", "class_d_a_q_driver.html", "class_d_a_q_driver" ],
    [ "DeviceControl", "class_device_control.html", "class_device_control" ],
    [ "DeviceDiscovery", "class_device_discovery.html", "class_device_discovery" ],
    [ "DeviceInfo", "class_device_info.html", "class_device_info" ],
    [ "DeviceStatus", "class_device_status.html", "class_device_status" ],
    [ "DiscoveredDevice", "class_discovered_device.html", "class_discovered_device" ],
    [ "EventLoopThread", "class_event_loop_thread.html", "class_event_loop_thread" ],
    [ "Formatting", "class_formatting.html", "class_formatting" ],
    [ "Heartbeat", "class_heartbeat.html", "class_heartbeat" ],
    [ "IEPE", "class_i_e_p_e.html", "class_i_e_p_e" ],
    [ "InputRange", "class_input_range.html", "class_input_range" ],
    [ "Message", "struct_message.html", "struct_message" ],
    [ "MessageDeserializer", "class_message_deserializer.html", "class_message_deserializer" ],
    [ "MessageHashTable", "class_message_hash_table.html", "class_message_hash_table" ],
    [ "MessageHeader", "struct_message_header.html", "struct_message_header" ],
    [ "MessageParser", "class_message_parser.html", "class_message_parser" ],
    [ "MessageProcessor", "class_message_processor.html", "class_message_processor" ],
    [ "MessageRouter", "class_message_router.html", "class_message_router" ],
    [ "MessageSerializer", "class_message_serializer.html", "class_message_serializer" ],
    [ "ServerSocketConnector", "class_server_socket_connector.html", "class_server_socket_connector" ],
    [ "Streaming", "class_streaming.html", "class_streaming" ],
    [ "Time", "class_time.html", "class_time" ],
    [ "Timer", "class_timer.html", "class_timer" ]
];