# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs depedencies necessary for building
    - name: Setup environment
      run: sudo apt -y install build-essential cmake libprotoc-dev doxygen graphviz git

    # Pull git submodules
    - name: Pull submodules
      run: git submodule sync --recursive
      
    # Runs cmake to generate makefiles
    - name: Run CMake
      run: |
        mkdir build
        cd build 
        cmake ..
    
    #Invoke make to start compiling the projects
    - name: Compile project
      run: make -j16
