# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    # The type of runner that the job will run on
    runs-on: windows-2019

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Pull git submodules
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update

    # Installs depedencies necessary for building
    - name: Setup environment
      run: powershell.exe -executionpolicy remotesigned -File Scripts/SetupEnvironment.ps1

    # Installs depedencies necessary for building
    - name: Generate Solution
      run: powershell.exe -executionpolicy remotesigned -File Scripts/GenerateSLN.ps1

    # Build Solution
    - name: Build Solution
      run: |
        powershell -command ""%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\msbuild.exe" /p:Configuration=Release /p:Platform=x64"
        powershell -command ""%programfiles(x86)%\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\msbuild.exe" /p:Configuration=Release /p:Platform=x86"

  build-ubuntu-2004:
    # The type of runner that the job will run on
    runs-on: 	ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs depedencies necessary for building
    - name: Setup environment
      run: sudo apt -y install build-essential cmake libprotoc-dev git protobuf-compiler

    # Pull git submodules
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update

    # Runs cmake to generate makefiles
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake ..

    #Invoke make to start compiling the projects
    - name: Compile project
      run: |
        cd build
        make -j16

  build-ubuntu-1804:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Installs depedencies necessary for building
    - name: Setup environment
      run: sudo apt -y install build-essential cmake libprotoc-dev git protobuf-compiler

    # Pull git submodules
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update

    # Runs cmake to generate makefiles
    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake ..

    #Invoke make to start compiling the projects
    - name: Compile project
      run: |
        cd build
        make -j16
